### ISSUE TITLE
Well done, I laughed 

### ISSUE THREAD

**Issue by innocentvoice** [Ayanokouj1-kun/Arcaea-Fanmades#1]
As title, hahaha. I'm always watching. Idk if you want to be famous or something but you should not share this to anybody tbh.

**Comment by Ayanokouj1-kun** [comment]
No worries lol that drive needs authorization first

**Comment by Ayanokouj1-kun** [comment]
Because I'm not selfish like the other modders, game supposed to be play they can grant access to me but they must pleased first.

**Comment by Ayanokouj1-kun** [comment]
And who the F are you? I've got basher already? Sryl mind your own business and mind your own manner did I make something to offend you to treat me like this? Just because of offsets issue? You kinda misunderstood me not to be rude but to be realistic.

**Comment by innocentvoice** [comment]
> And who the F are you? I've got basher already? Sryl mind your own business and mind your own manner did I make something to offend you to treat me like this? Just because of offsets issue? You kinda misunderstood me not to be rude but to be realistic.

I'm not trying to be rude, just a reminder to you

**Comment by innocentvoice** [comment]
> > And who the F are you? I've got basher already? Sryl mind your own business and mind your own manner did I make something to offend you to treat me like this? Just because of offsets issue? You kinda misunderstood me not to be rude but to be realistic.
> 
> I'm not trying to be rude, just a reminder to you

Be careful with what you did.
